name: Node.js CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2.3.4

      - name: Setup Nodejs environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build
        run: |
          npm install yarn 
          yarn install
          yarn build
      - name: git push 
        run: |
          git config --global user.email "1619686166@qq.com"&&git config --global user.name "Fullsize"
          git add build/*
          git commit -m 'update build'
          git push origin build
